### ISSUE TITLE
Error adding torrent

### ISSUE THREAD

**Issue by codxse** [Meshiest/mrseedbox#2]
hi,

Have finished install to Ubuntu 16.04, not-using root user. All works except adding torrent and magnet. 

Thanks.

**Comment by Meshiest** [comment]
@codxse Can you share some logs from `docker logs mrseedbox_backend_1` or `docker logs mrseedbox_transmisssion_1` ?

that sounds like your transmission daemon isn't properly setup.

Double check your docker-compose.yml or try connecting to `localhost:9091` with the username and password from your common.env!

**Comment by codxse** [comment]
Thanks @Meshiest for the response, somehow, sometimes it works. I re-deploy it again with new machine and it works. I don't know why. I will posted the logs when I got new error. Thanks.
