### ISSUE TITLE
No connection to rTorrent

### ISSUE THREAD

**Issue by RadicalBlue** [Meshiest/mrseedbox#7]
Hi again

Well, at first all seems to work perfectly but after several minutes ruTorrent lose connection with rtorrent and can't reconnect.
If I stop the containers (with ./stop) and restart (with ./start), it works again but it doesn't last long before, once again, rutorrent lose connection.
The webui log just says 

> No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

I looked on the files but I'm a newbie in that kind of things so I didn't really understand if there was a problem... I don't know where to find relevant logs either. So tell me where to find it and I'll post it if needed :)

thanks

**Comment by Meshiest** [comment]
That's a little weird!

Are there any errors in the mrseedbox_backend_1 logs?

**Comment by RadicalBlue** [comment]
I've got this which looks like an error :

>  172.17.0.7 - - [27/Mar/2017:07:38:24 UTC] "GET /api/torrents HTTP/1.0" 200 2
 https://domain.com/ -> /api/torrents
 Failed Fetching
 /usr/local/lib/ruby/gems/2.4.0/gems/xmlrpc-0.2.1/lib/xmlrpc/client.rb:509:in `do_rpc'
 /usr/local/lib/ruby/gems/2.4.0/gems/xmlrpc-0.2.1/lib/xmlrpc/client.rb:321:in `call2_async'
 /usr/local/lib/ruby/gems/2.4.0/gems/xmlrpc-0.2.1/lib/xmlrpc/client.rb:308:in `call_async'
 /usr/local/bundle/gems/retort-0.0.8/lib/retort/service.rb:24:in `call'
 /usr/local/bundle/gems/retort-0.0.8/lib/retort/torrent.rb:33:in `all'
 /app/app.rb:573:in `block in <class:Server>'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
 /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
 /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
 /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
 /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
 /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
 /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
 /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
 /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
 /usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
 /usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
 /usr/local/bundle/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
 /usr/local/bundle/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
 /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
/usr/local/bundle/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service' /usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/usr/local/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'

**Comment by Meshiest** [comment]
It looks like rtorrent is having some trouble!

Could you post the logs for mrseedbox_rtorrent_1 

Thanks!

**Comment by RadicalBlue** [comment]
here it is : 

 > [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> 
 > [s6-init] ensuring user provided files have correct perms...exited 0.
 > [fix-attrs.d] applying ownership & permissions fixes...
 > [fix-attrs.d] done.
 > [cont-init.d] executing container initialization scripts...
 > [cont-init.d] 10-adduser: executing...
> 
 > -------------------------------------
 >           _     _ _
 >          | |___| (_) ___
 >          | / __| | |/ _ \
 >          | \__ \ | | (_) |
 >          |_|___/ |_|\___/
 >                |_|
 > 
 > Brought to you by linuxserver.io
 > We gratefully accept donations at:
 > https://www.linuxserver.io/donations/
 > -------------------------------------
 > GID/UID
 > -------------------------------------
 > User uid:    1000
 > User gid:    1000
 > -------------------------------------
 > 
 > [cont-init.d] 10-adduser: exited 0.
 > [cont-init.d] 20-config: executing...
 > [cont-init.d] 20-config: exited 0.
 > [cont-init.d] done.
 > [services.d] starting services
 > [services.d] done.
 > ==> /config/log/rtorrent/rtorrent.log <==
 > ---END---
 > tail: cannot open '' for reading: No such file or directory

**Comment by Meshiest** [comment]
Can you double check to make sure your linked docker-compose volumes exist?

**Comment by RadicalBlue** [comment]
well, after I have done a reset (delete all, git clone and reconfigure all of it) it seems to works :) 

Thanks for all
